version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_network

  php:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./.docker/crontab:/etc/cron.d/crontab
      - ~/.ssh/:/root/.ssh
    user: "1000:www-data"
    env_file:
    - .env
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge

volumes:
  rabbitmq_data:
